[package]
name = "xelis-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
xelis-ast = { path = "../ast" }
xelis-types = { path = "../types" }
xelis-builder = { path = "../builder" }
xelis-environment = { path = "../environment" }