[package]
name = "xelis-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
xelis-ast = { path = "../ast" }
xelis-bytecode = { path = "../bytecode" }
xelis-types = { path = "../types" }
xelis-environment = { path = "../environment" }
thiserror = "2.0.1"

[dev-dependencies]
xelis-builder = { path = "../builder" }
xelis-lexer ={ path = "../lexer" }
xelis-parser = { path = "../parser" }