[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
ast = { path = "../ast" }
environment = { path = "../environment" }
thiserror = "2.0.1"
paste = "1.0.15"
